config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  match '/logout(/:id)', to: "users#destroy", as: "user_logout", via: [:get, :delete]
  get "new_signup/" , to: "users#new_signup" , as: "new_signup"
  post "user_signup/" , to: "users#user_signup" , as: "user_signup"
  get "login/" , to: "users#new_login" , as: "login"
  post "login/" , to: "users#user_login" , as: "user_login"
  get "activity/" , to: "users#activity" , as: "activity"
  
  root "users#index"

  get "index", to: "work_sessions#index", as: "work_session_index"
  post "clock_in", to: "work_sessions#clock_in", as: "clock_in_work_sessions"
  post "start_break", to: "work_sessions#start_break", as: "start_break_work_sessions"
  post "end_break", to: "work_sessions#end_break", as: "end_break_work_sessions"
  post "clock_out", to: "work_sessions#clock_out", as: "clock_out_work_sessions"
  get 'work_sessions/:id/my_work', to: 'work_sessions#my_work', as: 'my_work'

  get 'save_screenshot', to: 'screenshots#save_screenshot'
end

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
      }

      li {
        float: left;
      }

      li a {
        display: block;
        color: white;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
      }

      li a:hover {
        background-color: #111;
      }

      .top-right {
        position: absolute;
        top: 10px;
        right: 20px;
        background: #333;
        color: white;
        padding: 10px 15px;
        border-radius: 5px;
      }
      .top-right a {
        color: #f1c40f;
        text-decoration: none;
        margin-left: 10px;
      }
      .top-right a:hover {
        text-decoration: underline;
      }

    </style>
  </head>
  <body>
  <ul>

  <% if session[:user_id] %>
    <% @user = User.find_by(id: session[:user_id]) %>
    <% if @user %>
       <div class="top-right">
        Logged in as <strong><%= @user.username %></strong>.
        <%= link_to 'Logout', user_logout_path, method: :delete %>
      </div>
      <li><%= link_to 'Home', work_session_index_path %></li>
    <% end %>
  <% else %>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Signup', new_signup_path %></li>
    <li><%= link_to 'Login', login_path %></li>
  <% end %>
  </ul>
  
  </body>
</html>