config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  match '/logout(/:id)', to: "users#destroy", as: "user_logout", via: [:get, :delete]
  get "new_signup/" , to: "users#new_signup" , as: "new_signup"
  post "user_signup/" , to: "users#user_signup" , as: "user_signup"
  get "login/" , to: "users#new_login" , as: "login"
  post "login/" , to: "users#user_login" , as: "user_login"
  get "activity/" , to: "users#activity" , as: "activity"
  
  root "users#index"

  get "index", to: "work_sessions#index", as: "work_session_index"
  post "clock_in", to: "work_sessions#clock_in", as: "clock_in_work_sessions"
  post "start_break", to: "work_sessions#start_break", as: "start_break_work_sessions"
  post "end_break", to: "work_sessions#end_break", as: "end_break_work_sessions"
  post "clock_out", to: "work_sessions#clock_out", as: "clock_out_work_sessions"
  get 'work_sessions/:id/my_work', to: 'work_sessions#my_work', as: 'my_work'

  get 'save_screenshot', to: 'screenshots#save_screenshot'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :username, :phone_number, uniqueness: true, presence: true
    validates :password, presence: true, confirmation: true
    validates :password_confirmation, presence: true

    has_many :work_sessions, dependent: :destroy
    has_many :screenshots, dependent: :destroy

    def self.ransackable_attributes(auth_object = nil)
        ["address", "city", "username", "country", "created_at", "email", "first_name", "id", "id_value", "last_name", "password_digest", "phone_number", "role", "state", "updated_at", "zip_code", "work_sessions_id"]
    end

    def self.ransackable_associations(auth_object = nil)
        []
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:new_owner]

  def index
  end

  def new_signup
    @user = User.new
  end

  def activity
  end
  def user_signup
    @user = User.create(user_params)
    if @user.password != @user.password_confirmation
      flash[:error] = "password should be match"
    end
      
		if @user.save
			flash[:success] = "Account Sucessfully Created"
      redirect_to login_path
		else
			flash[:error] = @user.errors.full_messages
			render :new_signup
		end
  end

  def new_owner
		render :new_owner
	end

	def create_user
		@owner = User.new(owner_params)
		if @owner.save
			flash[:success] = "Owner Sucessfully Created"
      # OwnerMailer.with(user: @user).welcome_email.deliver_now  
      redirect_to admin_index_path
		else
			flash[:error] = @owner.errors.full_messages
			render :new_owner
		end
	end
  

  def new_login
		@user = User.new
	end

  def user_login
    @user = User.find_by(email: params[:email])
    if @user.present?
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:success] = "Login Sucessfully"
        redirect_to work_session_index_path
      else
        flash[:error] = "Invalid email or password"
        render :new_login
      end
    else
      flash[:error] = "No user found with this email"
      render :new_login
    end
  end

	def destroy
		if session[:user_id].present?
			session[:user_id] = nil
      stop_screenshot_capture(current_user.id)
			flash[:success] = 'User successfully logged out.'
		end
		redirect_to login_path
	end

  # def current_user
  #   if session[:user_id]
  #     @user = User.find_by(id: session[:user_id])
  #   else
  #     redirect_to login_path
  #     flash[:error] = "Must be login"
  #   end
  # end

  def current_user
    @user ||= User.find_by(id: session[:user_id])
    redirect_to login_path, flash: { error: "Must be logged in" } unless @user
  end

  private

  def stop_screenshot_capture(user_id)
    system("pkill -f 'python scripts/screenshot_uploader.py #{user_id}'")
  end

	def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :phone_number)
  end
end

app/views/users/activity.html.erb
<div>
    <h1 id="timer">00:00:00</h1>
    <button id="start-btn">Start</button>
    <button id="pause-btn">Pause</button>
</div>
<script>
let timerInterval;
let elapsedTime = 0;
let isRunning = false;

function startTimer() {
    if (!isRunning) {
        isRunning = true;
        let startTime = Date.now() - elapsedTime;

        timerInterval = setInterval(function () {
            elapsedTime = Date.now() - startTime;
            displayTime(elapsedTime);
        }, 1000);
    }
}

function pauseTimer() {
    isRunning = false;
    clearInterval(timerInterval);
}

function displayTime(milliseconds) {
    let totalSeconds = Math.floor(milliseconds / 1000);
    let hours = Math.floor(totalSeconds / 3600);
    let minutes = Math.floor((totalSeconds % 3600) / 60);
    let seconds = totalSeconds % 60;

    document.getElementById("timer").textContent = 
        (hours < 10 ? "0" : "") + hours + ":" + 
        (minutes < 10 ? "0" : "") + minutes + ":" + 
        (seconds < 10 ? "0" : "") + seconds;
}

document.addEventListener("DOMContentLoaded", function () {
    document.getElementById("start-btn").addEventListener("click", startTimer);
    document.getElementById("pause-btn").addEventListener("click", pauseTimer);
});
</script>

app/views/users/index.html.erb
<%= render partial: 'partials/header' %>

app/views/users/new_login.html.erb
<%= render partial: 'partials/header' %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    display: flex;
    height: 100vh;
    background-color: #343a40;
}
#container{
    margin:auto;
    display: flex;
    color:#f8f9fa;
    flex-direction: column;
    width:500px;
    box-shadow: 1px 2px 71px -6px rgba(0,0,0,0.67);
    height:fit-content;
    font-family:sans-serif;
    background-color: #212529;
    padding:25px 20px;
    border-radius: 10px;
}
#Heading{
    padding:15px;
    text-align: center;
    font-size: 2.5em;
    font-weight: 900;
}
label{
    font-size: 1.1em;
    font-weight: 500;
    margin:10px 0px;
}
input{
    padding:10px;
    border-top-right-radius: 10px;
    height: 50px;
    background-color: #6c757d;
    border-bottom-right-radius:10px;
    outline: none;
    border: none;
    font-size:19px;
    transition-duration: 0.15s;
    
    color:#f8f9fa;
}
input:focus{
    outline: none;
    background-color: none;
}
input::placeholder{
    color:#f8f9fa;
    font-size: 19.2px;
}
.row:not(.name){
    width:100%;
    height:fit-content;
    display: grid;
    grid-template-columns: 10% 90%;
    grid-template-rows: 50px;
}
.name{
    width:100%;
    height: fit-content;
    display: flex;
    margin-top:20px;

}
.name>input{
    width:calc(50% - 5px);
    margin:5px;
    border-radius: 10px;;
}
.icon{
    height: 50px;
    background-color: #6c757d;
    border-top-left-radius: 10px;
    padding:10px;
    margin-right:1px;
    border-bottom-left-radius: 10px;
    fill:white;
}
button{
    width:fit-content;
    margin:20px auto;
    padding:10px 20px;
    outline: none;
    border: none;
    border-radius: 20px;
    font-weight: 700;
    color:white;
    background-color: #248277;
    font-family:sans-serif;
    font-size: 1.1em;
    cursor: pointer;
    transition-duration: 0.25s;
}
button:hover{
    background-color: #036666;
}
span{
    display: flex;
    justify-content: flex-end;

}
a{
    text-decoration: none;
    color:#99e2b4;
}
span>span>a{
    margin:0px 5px
}
a:hover{
    color: #06d6a0;
}
#MsgBx{
    width:100%;
    position: absolute;
    top:0px;
    left:0px;
    height:auto;
    padding:20px;
}
#MsgBx>li{
    list-style: none;
    color: white;
    border-radius: 5px;
    padding:10px;
    background-color: #036666;
    width:fit-content;
    font-family: 'Ubuntu', sans-serif;
    position: relative;
    animation: enteranceError 1s ease;
    margin:5px;
}
input:focus{
    border:5px solid #06d6a0;
    height: 49px;
    margin-top:2px;
}

.flash-message {
  position: fixed;
  top: 10px;
  left: 55%;
  transform: translateX(-50%);
  background-color: #383c3900; 
  color: white;
  padding: 10px 20px;
  border-radius: 5px;
  text-align: center;
  font-size: 16px;
  font-weight: bold;
  z-index: 1000;
  display: inline-block;
}

.flash-message.alert {
  background-color: #dc3545; 
}


</style>
<body>
  <% flash.each do |type, message| %>
    <div class="flash-message <%= type %>">
      <%= message %>
    </div>
  <% end %>
  <%= form_with(model: @user, url: user_login_path) do |form| %>

  <h3 id="Heading">Login</h3>

  <%= form.label :email %>
  <div class="row">
      <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="100%"><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></div>
      <%= form.email_field :email, placeholder: 'Email', required: true %>
  </div>
  <br>
  <%= form.label :password %>
  <div class="row">
      <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="30px"><path d="M336 352c97.2 0 176-78.8 176-176S433.2 0 336 0S160 78.8 160 176c0 18.7 2.9 36.8 8.3 53.7L7 391c-4.5 4.5-7 10.6-7 17v80c0 13.3 10.7 24 24 24h80c13.3 0 24-10.7 24-24V448h40c13.3 0 24-10.7 24-24V384h40c6.4 0 12.5-2.5 17-7l33.3-33.3c16.9 5.4 35 8.3 53.7 8.3zM376 96a40 40 0 1 1 0 80 40 40 0 1 1 0-80z"/></svg></div>
      <%= form.password_field :password, placeholder: 'Password', required: true %>
  </div>
  <br>
  <button type="submit">Login</button>
  <br>
  <% end %>
</body>
</html>

app/views/users/new_signup.html.erb
<%= render partial: 'partials/header' %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    *{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    display: flex;
    height: 100vh;
    background-color: #343a40;
}
#container{
    margin:auto;
    display: flex;
    color:#f8f9fa;
    flex-direction: column;
    width:500px;
    box-shadow: 1px 2px 71px -6px rgba(0,0,0,0.67);
    height:fit-content;
    font-family:sans-serif;
    background-color: #212529;
    padding:25px 20px;
    border-radius: 10px;
}
#Heading{
    padding:15px;
    text-align: center;
    font-size: 2.5em;
    font-weight: 900;
}
label{
    font-size: 1.1em;
    font-weight: 500;
    margin:10px 0px;
}
input{
    padding:10px;
    border-top-right-radius: 10px;
    height: 50px;
    background-color: #6c757d;
    border-bottom-right-radius:10px;
    outline: none;
    border: none;
    font-size:19px;
    transition-duration: 0.15s;
    
    color:#f8f9fa;
}
input:focus{
    outline: none;
    background-color: none;
}
input::placeholder{
    color:#f8f9fa;
    font-size: 19.2px;
}
.row:not(.name){
    width:100%;
    height:fit-content;
    display: grid;
    grid-template-columns: 10% 90%;
    grid-template-rows: 50px;
}
.name{
    width:100%;
    height: fit-content;
    display: flex;
    margin-top:20px;

}
.name>input{
    width:calc(50% - 5px);
    margin:5px;
    border-radius: 10px;;
}
.icon{
    height: 50px;
    background-color: #6c757d;
    border-top-left-radius: 10px;
    padding:10px;
    margin-right:1px;
    border-bottom-left-radius: 10px;
    fill:white;
}
button{
    width:fit-content;
    margin:20px auto;
    padding:10px 20px;
    outline: none;
    border: none;
    border-radius: 20px;
    font-weight: 700;
    color:white;
    background-color: #248277;
    font-family:sans-serif;
    font-size: 1.1em;
    cursor: pointer;
    transition-duration: 0.25s;
}
button:hover{
    background-color: #036666;
}
span{
    display: flex;
    justify-content: flex-end;

}
a{
    text-decoration: none;
    color:#99e2b4;
}
span>span>a{
    margin:0px 5px
}
a:hover{
    color: #06d6a0;
}
#MsgBx{
    width:100%;
    position: absolute;
    top:0px;
    left:0px;
    height:auto;
    padding:20px;
}
#MsgBx>li{
    list-style: none;
    color: white;
    border-radius: 5px;
    padding:10px;
    background-color: #036666;
    width:fit-content;
    font-family: 'Ubuntu', sans-serif;
    position: relative;
    animation: enteranceError 1s ease;
    margin:5px;
}
input:focus{
    border:5px solid #06d6a0;
    height: 49px;
    margin-top:2px;
}

.flash-message {
  position: fixed;
  top: 10px;
  left: 55%;
  transform: translateX(-50%);
  background-color: #383c3900; 
  color: white;
  padding: 10px 20px;
  border-radius: 5px;
  text-align: center;
  font-size: 16px;
  font-weight: bold;
  z-index: 1000;
  display: inline-block;
}

.flash-message.alert {
  background-color: #dc3545; 
}

</style>
<body>
  <% flash.each do |type, message| %>
    <div class="flash-message <%= type %>">
      <%= message %>
    </div>
  <% end %>

  <%= form_with(model: @user ,url: user_signup_path ) do |form| %>
    <h3 id="Heading">Sign Up</h3>


    <%= form.label :username %>
    <div class="row">
      <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="100%"><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></div>
      <%= form.text_field :username, placeholder: 'Username', required: true %>
    </div>

    <% if @user.errors[:username].any? %>
      <p style="color: white; font-size: 14px;"><%= @user.errors[:username].first %></p>
    <% end %>
    <br>
    
    <%= form.label :email %>
    <div class="row">
      <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="100%"><path d="M48 64C21.5 64 0 85.5 0 112c0 15.1 7.1 29.3 19.2 38.4L236.8 313.6c11.4 8.5 27 8.5 38.4 0L492.8 150.4c12.1-9.1 19.2-23.3 19.2-38.4c0-26.5-21.5-48-48-48H48zM0 176V384c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V176L294.4 339.2c-22.8 17.1-54 17.1-76.8 0L0 176z"/></svg></div>
      <%= form.email_field :email, placeholder: 'Email', required: true %>
    </div>

    <% if @user.errors[:email].any? %>
      <p style="color: white; font-size: 14px;"><%= @user.errors[:email].first %></p>
    <% end %>
    <br>
    <%= form.label :phone_number %>
    <div class="row">
      <div class="icon"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="100%"><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg></div>
      <%= form.text_field :phone_number, placeholder: 'Contact', required: true %>
    </div>
    <% if @user.errors[:phone_number].any? %>
      <p style="color: white; font-size: 14px;"><%= @user.errors[:phone_number].first %></p>
    <% end %>
    <br>
    <%= form.label :password %>
    <div class="row">
      <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="30px">
          <path d="M336 352c97.2 0 176-78.8 176-176S433.2 0 336 0S160 78.8 160 176c0 18.7 2.9 36.8 8.3 53.7L7 391c-4.5 4.5-7 10.6-7 17v80c0 13.3 10.7 24 24 24h80c13.3 0 24-10.7 24-24V448h40c13.3 0 24-10.7 24-24V384h40c6.4 0 12.5-2.5 17-7l33.3-33.3c16.9 5.4 35 8.3 53.7 8.3zM376 96a40 40 0 1 1 0 80 40 40 0 1 1 0-80z"/>
        </svg>
      </div>
      <%= form.password_field :password, placeholder: 'Password', required: true %>
    </div>
    <% if @user.errors[:password].any? %>
      <p style="color: red; font-size: 14px;"><%= @user.errors[:password].first %></p>
    <% end %>
    <br>
    
    <%= form.label :password_confirmation %>
    <div class="row">
      <div class="icon">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="30px">
          <path d="M336 352c97.2 0 176-78.8 176-176S433.2 0 336 0S160 78.8 160 176c0 18.7 2.9 36.8 8.3 53.7L7 391c-4.5 4.5-7 10.6-7 17v80c0 13.3 10.7 24 24 24h80c13.3 0 24-10.7 24-24V448h40c13.3 0 24-10.7 24-24V384h40c6.4 0 12.5-2.5 17-7l33.3-33.3c16.9 5.4 35 8.3 53.7 8.3zM376 96a40 40 0 1 1 0 80 40 40 0 1 1 0-80z"/>
        </svg>
      </div>
      <%= form.password_field :password_confirmation, placeholder: 'Confirm Password', required: true %>
    </div>
    <% if @user.errors[:password_confirmation].any? %>
      <p style="color: red; font-size: 14px;"><%= @user.errors[:password_confirmation].first %></p>
    <% end %>
    
    <button type="submit">Sign Up</button>
    <%= link_to root_path do %>
      <button type="button">GoTo Home</button>
    <% end %>
    
    <br>
    <%= link_to 'Already Have Acount? Login', login_path %>
  <% end %>
</body>
</html>